// packages/extension/src/vue/comp/AudioVisualizer.vue
<script lang="ts" setup>
import { watch, ref } from "vue";

const props = defineProps<{
  audio_stream: MediaStream;
}>();
let ref_canvas: any = ref(null);

let methods = {
  async visualize(stream) {
    // console_log("visualizer_run");
    // workaround for activating the stream:
    // https://stackoverflow.com/questions/54514273/webrtc-via-web-audio-api-silent-on-google-chrome
    let audio = new Audio();
    audio.srcObject = stream;
    audio.muted = true;
    //
    var canvas_arr = [ref_canvas.value];

    // console_log("canvas_arr", canvas_arr);
    var ctx_arr = canvas_arr.map((canvas) => {
      return canvas.getContext("2d");
    });

    function renderFrame() {
      requestAnimationFrame(renderFrame);
      x = 0;

      analyser.getByteFrequencyData(dataArray);

      // console_log("renderFrame", dataArray);
      ctx_arr.forEach((ctx) => {
        if (!ctx) return;
        ctx.fillStyle = "#fff";
        ctx.fillRect(0, 0, WIDTH, HEIGHT);
      });

      for (var i = 0; i < bufferLength; i++) {
        barHeight = dataArray[i] / 2;
        var r = 124 * 1; //(barHeight / 80);
        var g = 7 * 1; //(barHeight / 80);
        var b = 60 * 1; //(barHeight / 80);

        ctx_arr.forEach((ctx) => {
          if (!ctx) return;
          ctx.fillStyle = `rgb( ${r}, ${g}, ${b} )`;
          ctx.fillRect(x, HEIGHT - barHeight / 2, barWidth, barHeight);
        });

        x += barWidth + 1;
      }
    }

    var audioCtx = new AudioContext();

    var analyser = audioCtx.createAnalyser();

    let src = audioCtx.createMediaStreamSource(stream);

    src.connect(analyser);
    // analyser.connect( audioCtx.destination );
    analyser.fftSize = 256;

    var bufferLength = analyser.frequencyBinCount;

    var dataArray = new Uint8Array(bufferLength);

    if (canvas_arr[0]) {
      var WIDTH = canvas_arr[0].width;
      var HEIGHT = canvas_arr[0].height;

      var barWidth = (WIDTH / bufferLength) * 2.5;
      var barHeight;
      var x = 0;

      renderFrame();
    }
  },
};
watch(
  () => [props.audio_stream, ref_canvas.value],
  () => {
    // console_log("visualizer_check", props.audio_stream, ref_canvas.value);
    if (props.audio_stream && ref_canvas.value) {
      methods.visualize(props.audio_stream);
    }
  },
  {
    deep: true,
    immediate: true,
  }
);
</script>

<template>
  <canvas ref="ref_canvas" class="audio-visualizer" height="100" width="500">
  </canvas>
</template>

<style>
.audio-visualizer {
  position: relative;

  top: 0px;
  left: 0px;
  width: 100%;
  height: 100%;

  border-radius: 4px;

  opacity: 0.6;
}
</style>

// packages/proton-record-react/src/AudioVisualizer.tsx
import { useEffect, useRef } from "react";

type AudioVisualizerProperties = {
  audioStream: MediaStream | null;
};

function AudioVisualizer(properties: AudioVisualizerProperties) {
  const canvasReference = useRef<HTMLCanvasElement | null>(null);

  useEffect(() => {
    const canvasElement = canvasReference.current;
    if (canvasElement === null) {
      return;
    }

    const renderingContext = canvasElement.getContext("2d");
    if (renderingContext === null) {
      return;
    }

    const stream = properties.audioStream;
    if (stream === null) {
      renderingContext.clearRect(0, 0, canvasElement.width, canvasElement.height);
      return;
    }

    if (stream.getAudioTracks().length === 0) {
      renderingContext.clearRect(0, 0, canvasElement.width, canvasElement.height);
      return;
    }

    const audioContext = new AudioContext();
    const analyser = audioContext.createAnalyser();
    analyser.fftSize = 256;

    const source = audioContext.createMediaStreamSource(stream);
    source.connect(analyser);

    const frequencyBinCount = analyser.frequencyBinCount;
    const dataArray = new Uint8Array(frequencyBinCount);
    const barWidth = (canvasElement.width / frequencyBinCount) * 2.4;

    let animationFrameIdentifier = 0;

    const renderFrame = () => {
      animationFrameIdentifier = window.requestAnimationFrame(renderFrame);
      analyser.getByteFrequencyData(dataArray);

      renderingContext.fillStyle = "#ffffff";
      renderingContext.fillRect(0, 0, canvasElement.width, canvasElement.height);

      let xPosition = 0;
      for (let index = 0; index < frequencyBinCount; index += 1) {
        const barHeight = dataArray[index] * 0.5;
        // renderingContext.fillStyle = "rgb(124, 7, 60)";
        renderingContext.fillStyle = "rgb(88, 23, 209)";
        renderingContext.fillRect(xPosition, canvasElement.height - barHeight, barWidth, barHeight);
        xPosition += barWidth + 1;
      }
    };

    renderFrame();

    return () => {
      window.cancelAnimationFrame(animationFrameIdentifier);
      source.disconnect();
      analyser.disconnect();
      void audioContext.close();
    };
  }, [properties.audioStream]);

  return (
    <canvas
      className="audio-visualizer-canvas"
      ref={canvasReference}
      height={100}
      width={500}
    />
  );
}

export default AudioVisualizer;
